baseurl = "https://rohan.netlify.com/"
languageCode = "en-us"
title = "Rohan Karanth"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    github = "rmk4mk"
    linkedin = "rohankaranth19"
    # Disqus shortname
    disqus = "Your disqus shortname"
    # Google Analytics API key.
    ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    mixpanel_api_key = "Your Mixpanel API key"
    author = "Rohan Karanth"
    avatar = "C:/Users/Rohan Karanth/Documents/iXperience/Data Science/blog/hugo-identity-theme/static/images/avatars/rohan.jpg"
    contact = "rmk4mk@virginia.edu"
    bio = "Rohan Karanth is plain awesome. He’s a rising third year at UVA majoring in Systems Engineering. Follow this blog for interesting articles, posts, and analyses. Any feedback you have for me is greatly appreciated."
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Short subtitle/tagline of your blog"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.